version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: dnc_api_rest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2659
      MYSQL_DATABASE: dnc_api_rest
      MYSQL_USER: user1
      MYSQL_PASSWORD: 2659
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
